spring:
  data:
    mongodb:
      uri: mongodb+srv://brownyc6:digzOppQZVjXvjSc@cluster0.ododdsx.mongodb.net/
      database: testdb
  thymeleaf:
    cache: false

server:
  port: 8080

de.flapdoodle.mongodb.embedded.version: 8.0.10

data:
  init: false