spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  thymeleaf:
    cache: false

server:
  port: 8080

de.flapdoodle.mongodb.embedded.version: 8.0.10

data:
  init: false